= The Performance Tracking System (PTS), and a Task Group for it
////
SPDX-License-Identifier: CC-BY-4.0

Document conventions:
- one line per paragraph (don't fill lines - this makes changes clearer)
- Wikipedia heading conventions (First word only capitalized)
- US spelling throughout.
////

== Overview

=== Scope

The proposal aims to build a performance tracking system (PTS) for V8, OpenJDK, and other performance critical open source software in the RISC-V ecosystem.
The system includes a set of scripts for building the softwares we care about and running benchmarks, a farm of machines (hardwares), and a website to show the performance data.
The idea and implementation are based on the arewefastyet open-source project originated from Mozilla.

After the system is set up, we may need a task group for determining which hardware, which software, which benchmarks should be added into the system.
The task group may share the meeting with code speed opt SIG, for the people attending the two groups are almost the same.

The main difference of the perf tracking system and general/upstream CI/CD system is that the PTS is focusing on getting real performance data, hence it should always run on physical hardware, and different hardware has different performance characteris.

We aim to track V8 and OpenJDK projects in the first place, and include GCC, Clang/LLVM, Spidermonkey, Rust, Golang, Haskell, OCaml, Wasmtime and LuaJIT, etc in near future.

We are also targeting OpenBLAS and other important HPC/AI libraries in future.

=== RISC-V market justification

RISC-V is expanding its ecosystem boundary. It got popular in the embedded area in the past years, and now it is targeting server, mobile, AI, and other areas.
The Code Speed (performance) is blocking the prosperity of RISC-V on Desktop/HPC/Mobile fields.
Java speed on RV was ~100x slower than x86/Arm w/o JIT.
V8 and other runtimes w/ JITs are under optimized for RISC-V.
GCC and Clang still have huge potential to improve.
It is important to know where we are, how far can we achieve.
We need a platform to track the opportunities and measure our progress.
It is a kind of public goods, lighthouse for toolchains & runtimes & libs.
So, it is better to put under the umbrella of RISC-V International.

=== Document history

[cols="<2,<2,<3,<7",options="header,pagewidth",]
|================================================================================
| _Revision_ | _Date_        | _Author_ | _Modification_
| 0.2       | 2021-1-3   |

Wei Wu <wuwei2016@iscas.ac.cn>|

Update the proposal after meeting 2020-12-17.

| 0.1       | 2020-12-15   |

Wei Wu <wuwei2016@iscas.ac.cn>|

Initial version for discussion.

|================================================================================

== Requirements

=== Context

The performance tracking system has these type of objects:

* the repo we care about. Currently has GCC, LLVM, V8, OpenJDK, OpenBLAS.
* the hardware/machine we care about. Currently has Hifive Unleashed.
* the benchmarks we want to measure. Currently we have SunSpider/Octane/Kraken for JavaScript, SPECjvm98 for OpenJDK, and Embench for GCC/Clang.
* the combinations of building configs and running configs for the compilers/libs we wan to track.

=== Phasing

* Phase 1: set up the infrastructure
  - one compiler (v8), one board (unleashed), three (JS) benchmarks
  - One engineer, in one month. Run the process. Make the website online.

* Phase 2: more toolchains & runtimes, all available open-source benchmarks.
  - Include upstream GCC, RISC-V GCC, upstream Clang/LLVM
  - Include OpenJDK/HotSpot, OpenJDK/OpenJ9
  - Include Rust, Golang, and Wasmtime
  - Include Embench and all available open-source benchmarks

* Phase 3: more compilers, runtimes, physical boards and libraries
  - Add Hifive Unmatched and other physical boards, like Alibaba, etc.
  - Add more compilers & runtimes for academic and domain specific languages, like Haskell, OCaml, Julia, R, etc.
  - Set up APIs or processes to let RVI members run the scripts on their own devices and upload to the platform/website. (The idea is much like the submitting process of spec.org )
  - Include OpenBLAS and other compute libs.

=== Outline plan and timescale

* Phase 1: 1 engineer. 1 month. Plan: 2021-2-1 ~ 2021-3-1
  - Leave one month for volunteers. Can start today, although.
* Phase 2: 2 engineer. 3 month. Plan: 2021-3-1 ~ 2021-6-1
* Phase 3: 2 engineer. 2 month[1]. Plan: 2021-6-1 ~ 2021-8-1
  - [1] it depends on the status of hardware.
* Phase 4: Govern by a Perf Tracking TG.

After the building of infrastructure got done, a Task Group is needed to determine which repo should be added, which benchmark should be imported. and how to analyze and report the performance data we get.
The new task group may share the meeting time with code speed opt SIG.

=== Prerequisites

Contributors taking this project needs:

* Basic knowledge about performance testing and tuning
* Basic knowledge about how to establish a website and tuning JS and PHP code.
* Have RISC-V physical board (not necessary if you just want a test)
* Basic knowledge about how to write bash and python scripts.


=== Deliverables

* An open-source toolset for building compilers & running benchmarks & showing perf results on the web.
* Potential optimization opportunities and regressions uncovered by the PTS.
* Annual progress report of all the compilers, runtimes, libraries under the tracking of the PTS.

A monthly report to the SIG is a routine deliverables for all projects, which will cover
- key progress in the past month
- table showing tasks to be done, in progress, complete and verified
- test/benchmark results
- updates to the risk register
- plans for the next month

=== Milestones

It is a small project in the first place so the milestone is the phase stage itself.

=== Costs

* equipment costs
  - Plan to get more physical boards donated by the member companies which made them.
  - An VPS/IaaS for hosting the website. PLCT has an existing VPS and can donate for it.
* license costs
  - Use free & open benchmark first.
  - The non-free benchmarks are under investigation. How to donate? Is it possible? (due the LICENSE of each benchmark)
* personnel costs
  - In the first phase a professional engineer might need 80 hours to get all things done.
  - After the website and hardware farm were established, roughly one engineer one day (8 hours) per week.

== Risk register

TBD. The PLCT Lab is willing to contribute engineers.

Risks are assessed by the Impact (I) they have on the project from 1 (minor) to project killer (3) and by the Likelihood (L) of the risk occurring from 1 (10% chance) through 10 (100% chance).  The two are multiplied to give an overall Risk Factor (R).  Mitigation must be provided for any risk with I = 3 or R >= 10.

[cols="<4,1,1,1,<4",options="header,pagewidth",]
|=============================================================================
| _Risk_  | _I_ | _L_ | _R_ | _Mitigation_
| No silicon available for testing | 3 | 2 | 6 | Use cycle accurate models. Persuading more companies to donate.
| Too few engineers committed by members | 3 | 1  | 6 | RISC-V International to fund contract engineers to do the work.
| Too slow progress made by the projects under tracking | 1 | 8  | 8 | Raise this status to software SC or TSC/CTO.
|=============================================================================

The risk register will be maintained on an ongoing basis.

== Support

* Physical boards are needed.
  - Especially the boards that can run Linux are welcome.
* Members can run scripts in their own boards and upload the data.
* Need commercial toolchains & runtimes to run the scripts and send back the performance data to the tracking platform.


Table of member organizations and commitments

[cols="<4,<4,1,1,1",options="header,pagewidth",]
|=============================================================================
| _Organization_  | _Commitment_ | _Past_ | _2021_ | _2022_
| PLCT Lab.       | 12 engineer months compiler expertise; VM for website; hardware | X | X | X
| StarFive        | Hardware: Hifive Unleashed; Unmatched; | X | X | TBD
| ICT, CAS        | Open Source RISC-V Core & FPGA emulation platform  | N/A | X | X
| Nuclei System Technology        | Nuclei DDR 200T FPGA Evaluation Board, Supporting Nuclei 200/300/600/900  | N/A | X | X
|=============================================================================
