
= Infrastructure for Performance Tracking Project (Task Group)
////
SPDX-License-Identifier: CC-BY-4.0

Document conventions:
- one line per paragraph (don't fill lines - this makes changes clearer)
- Wikipedia heading conventions (First word only capitalized)
- US spelling throughout.
////

This is the outline template for developing project proposals

== Overview

=== Scope

Build a performance tracking system for RISC-V ecosystem.
It includes a set of scripts building SUT and running benchmarks, a farm of machines (hardwares), and a website to show the data points.
Based on the arewefastyet open-source project originated from Mozilla.

Running on physical boards. Get real performance data.
Targeting GCC, Clang/LLVM, V8, Spidermonkey, OpenJDK, Rust, Golang, and LuaJIT, etc.
Also targeting OpenBLAS and other important libraries in future.
Using Both free and commerical Benchmarks.

=== RISC-V market justification

The Code Speed (performance) is blocking the prosperity of RISC-V on Desktop/HPC/Mobile fields.
Java speed on RV was ~100x slower than x86/Arm w/o JIT.
V8 and other runtimes w/ JITs are under optimized for RISC-V.
GCC and Clang still have huge potential to improve.
It is important to know where we are, how far can we achieve.
We need a platform to tracking the oppotunities and measure our progress.
It is kind of public goods, lighthouse for toolchains & runtimes & libs.
So, it is better to put under the umbrella of RISC-V International.

=== Document history

[cols="<2,<2,<3,<7",options="header,pagewidth",]
|================================================================================
| _Revision_ | _Date_        | _Author_ | _Modification_
| 0.1       | 2020-12-15   |

Wei Wu <wuwei2016@iscas.ac.cn>|

Initial version for discussion.

|================================================================================

== Requirements

=== Context

The performance tracking system has these type of objects:

* the repo we care about. Currently has GCC, LLVM, V8, OpenJDK, OpenBLAS.
* the hardware/machine we care about. Currently has Hifive Unleashed.
* the benchmarks we want to measure. Currently we have SunSpider/Octane/Kraken for JavaScript, and mBench for GCC/Clang.
* the combinations of building configs and running configs for the compilers/libs we wan to track.

=== Phasing

* Phase 1: set up the infrastructure
  - one compiler (v8), one board (unleashed), three (JS) benchmarks
  - One engineer, in one month. Run the process. Make the website online.

* Phase 2: more toolchains & runtimes, all available open-source benchmarks.
  - Include upsteram GCC, RISC-V GCC, upstream Clang/LLVM
  - Include OpenJDK/HotSpot, OpenJDK/OpenJ9
  - Include Rust
  - Include Go
  - Include mBench and all available open-source benchmarks

* Phase 3: more physcial boards and libraries
  - Add Hifive Unmatched and other physical boards
  - Set up APIs or processes to let RVI members run the scripts on their own devices and upload to the platform/website.
  - Inlcude OpenBLAS and other compute libs.

=== Outline plan and timescale

* Phase 1: 1 engineer. 1 month. Plan: 2021-2-1 ~ 2021-3-1
  - Leave one month for volunteers. Can start today, although.
* Phase 2: 2 engineer. 3 month. Plan: 2021-3-1 ~ 2021-6-1
* Phase 3: 2 engineer. 2 month[1]. Plan: 2021-6-1 ~ 2021-8-1
  - [1] it depends on the status of hardware.
* Phase 4: Govern by a Perf Tracking TG.

After the building of infrastructure got done, a Task Group is needed to determine which repo should be added, which benchmark should be imported. and how to analyze and report the performance data we get.

=== Prerequisites

Contributors taking this project needs:

* Basic knowledge about performance testing and tuning
* Basic knowledge about how to establish a website and tuning JS and PHP code.
* Have RISC-V physical board (not necessary if you just want a test)
* Basic knowledge about how to write bash and python scripts.


=== Deliverables

* An open-source toolset for building compilers & running benchmarks & show perf results on web.
* Data reports generated by this tracking platform.

A monthly report to the SIG is a routine deliverables for all projects, which will cover
- key progress in the past month
- table showing tasks to be done, in progress, complete and verified
- test/benchmark results
- updates to the risk register
- plans for the next month

=== Milestones

I think it is just a small project in the first place so the milestone is the phase stage itself.

=== Costs

* equipment costs
  - Can we just get some boards donated by the member companies made them?
  - An VPS/IaaS for hosting the website. PLCT has existing VPS and can donate for it.
* license costs
  - Use free & open benchmark first.
  - How to donate? Is it possible? (due the LINCENSE of each benchmarks)
* personnel costs
  - TBD. Roughly 2 person 1 day per week?

== Risk register

TBD. The PLCT Lab is willing to contribute engineers.

Risks are assessed by the Impact (I) they have on the project from 1 (minor) to project killer (3) and by the Likelihood (L) of the risk occurring from 1 (10% chance) through 10 (100% chance).  The two are multiplied to give an overall Risk Factor (R).  Mitigation must be provided for any risk with I = 3 or R >= 10.

[cols="<4,1,1,1,<4",options="header,pagewidth",]
|=============================================================================
| _Risk_  | _I_ | _L_ | _R_ | _Mitigation_
| No silicon available for testing | 2 | 6 | 12 | Use cycle accurate models
| Too few engineers committed by members |

3 | 2  | 6 |

RISC-V International to fund contract engineers to do the work
|=============================================================================

The risk register will be maintained on an ongoing basis.

== Support

* Physical boards are needed.
  - Especially the boards that can run Linux are welcome.
* Members can run scripts in their own boards and upload the data.
* Need commercial toolchains & runtimes run the scripts and send back the performance data to the tracking platform.


Table of member organizations and commitments

[cols="<4,<4,1,1,1",options="header,pagewidth",]
|=============================================================================
| _Organization_  | _Commitment_ | _Past_ | _2021_ | _2022_
| PLCT Lab.       | 12 engineer months compiler expertise | X | X |
| Welcome Inc        | €50k funding |     |     | X
| ...             | ...          | ... | ... | ...
|=============================================================================
