:leveloffset: 1
= RISC-V Code Speed Optimization SIG Meeting Minutes =

Monday 16 November 2020, 07:00 Pacific Time

////
SPDX-License-Identifier: CC-BY-4.0

Document conventions:
- one line per paragraph (don't fill lines - this makes changes clearer)
- Wikipedia heading conventions (First word only capitalized)
- US spelling throughout.
////

== Summary of actions

* **Jeremy Bennett.** Clarify wording around faciliating consortia.
* **Jeremy Bennett.** Submit final charter to TWG for ratification.
* **Jeremy Bennett.** Advise Toolchain & Runtimes SC they need to own the list of software maintained by RISC-V International.
* **Jeremy Bennett.** Update list of potential projects.
* **Jeremy Bennett.** Advise Toolchain & Runtimes SC that they need to track libraries of interest to RISC-V International.

== Review of actions

* *Mark Himelstein* to advise how to access the free advertising for the commercial ecosystem

** complete - information circulated via the mailing list.

* *Jeremy Bennett* to collect comments on the charter and prepare an updated version for the next weeting.

** complete

* *Jeremy Bennett* to create the candidate project list in GitHub, so it can be updated by pull request and issue submission.

** complete.

* *Jim Wilson* to provide his list of GCC improvements.

** complete.

== Welcome

Attendees introduced themselves.

== Review the charter

Question of whether we can facilitate as a consortium. Probably need to do by escalation. Forming consortia would need to be outside RISC-V International.

**ACTION:** Jeremy Bennett. Clarify wording around faciliating consortia.

Subject to clarification of the point above, approved _nem. con._

**ACTION:** Jeremy Bennett. Submit final charter to TSC for ratification.

== List of candidate projects

Add the following.

* lots of language support. Set up baseline of code speed for each language

** see RISC-V software list maintained by RISC-V International
** This should be owned by Toolchain & Runtimes SC
** **ACTION:** Jeremy Bennett. Advise Toolchain & Runtimes SC they need to own the list of software maintained by RISC-V International
** Chinese Academy of Sciences PLCT Lab have infrastructure

* need list of benchmarks (see existing proposed project).

* loop level profiling, compilers support for profiling

* how does code density affect code speed, including cache impacts

* LLVM optimizations

* Other compiler optimizations

**ACTION:** Jeremy Bennett. Update list of potential projects.

=== Prioritization

Each person present was asked to choose their top two priorities for projects to work on

[cols="<4,>1",options="header,pagewidth",]
|=============================================================================
| _Project_                                                 | _Count_
| Continuous integration and test, benchmarking and tracing |      8
| Compiler optimizations for upcoming extensions            |      7
| Allocation of vendor specific relocations                 |      3
| GCC optimizations                                         |      2
| Linker related optimization                               |      2
| Documentation                                             |      1
| Making best use of existing optimizations                 |      1
|=============================================================================

At our next meeting we will tackle the first two of these

- **Wei Wu** (co-chair) will lead the discussion on continuous integration adn test, benchmarking and tracing
- **Jeremy Bennett** (chair) will led the discussion on compiler optimizations for upcoming extensions

== Dates of future meetings

The group meets at 07:00 Pacific Time

- Monday 7 December 2020
- Thereafter first Monday of the month throughout 2021

Mark Himelstein noted we can have more meetings if we need to.

== AOB

News from Chinese Academy of Sciences PLCT Lab

- Now have OpenJDK with basic RV64G porting. 50KLOC.
- Working on optimization OpenCV.

The SIG's role is to optimize libraries for speed, however there is a wider question of tracking which libraries matter to RISC-V International.

**ACTION:** Jeremy Bennett.  Advice Toolchain & Runtimes SC that they need to track libraries of interest to RISC-V.

Jeremy Bennett, Candidate Chair +
Wei Wu, Candidate Co-chair
